version: '3.8'

services:
  kibou:
    image: kibou-registery
    build: .
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD:  ${SPRING_DATASOURCE_PASSWORD}
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: Algomath kibou-registry
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
