version: '3.8'

services:
  kibou:
    image: kibou-registery
    build: .
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.railway.internal:5432/railway
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: HGrDwAsZOQMYlQjvmDZXegXlhjselnAl
    depends_on:
      - db

  db:
    image: postgres:alpine
      environment:
        POSTGRES_DB: railway
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: HGrDwAsZOQMYlQjvmDZXegXlhjselnAl
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
