spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST}:${PGPORT}/${POSTGRES_DB}}
      username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER}}
      password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:9000}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
