spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres.railway.internal:5432/railway}
      username: ${SPRING_DATASOURCE_USERNAME:postgres}
      password: ${SPRING_DATASOURCE_PASSWORD:HGrDwAsZOQMYlQjvmDZXegXlhjselnAl}


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:9000}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
