name: Commit Message Check

on: [push]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if Merge Commit
        id: check-merge
        run: |
          is_merge_commit=$(git log -1 --pretty=%P | wc -w)
          echo "is_merge_commit=$is_merge_commit" >> $GITHUB_ENV
          echo "::set-output name=is_merge::$(if [ "$is_merge_commit" -gt 1 ]; then echo 'true'; else echo 'false'; fi)"

      - name: Check Commit Message
        if: env.is_merge_commit == '1'
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(feat|chore|test|fix|perf|doc|refactor):'
          error: 'Commit message does not start with "feat:", "chore:", "test:", "fix:", "perf:", "doc:", or "refactor"'

      - name: Check Commit Message Length
        if: env.is_merge_commit == '1'
        run: |
          commit_message=$(git log -1 --pretty=%B)
          min_length=15
          actual_length=${#commit_message}
          if [ $actual_length -lt $min_length ]; then
            echo "Commit message is too short. It must be at least $min_length characters."
            echo "Actual message: '$commit_message'"
            echo "Actual length: $actual_length"
            echo "Required length: $min_length"
            exit 1
          fi
